/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule.aim;

public class AndroidOutImageRead_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AndroidOutImageRead_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndroidOutImageRead_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_AndroidOutImageRead_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSuccess(boolean value) {
    AIMJNI.AndroidOutImageRead_t_success_set(swigCPtr, this, value);
  }

  public boolean getSuccess() {
    return AIMJNI.AndroidOutImageRead_t_success_get(swigCPtr, this);
  }

  public void setVal(vector_int value) {
    AIMJNI.AndroidOutImageRead_t_val_set(swigCPtr, this, vector_int.getCPtr(value), value);
  }

  public vector_int getVal() {
    long cPtr = AIMJNI.AndroidOutImageRead_t_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public AndroidOutImageRead_t() {
    this(AIMJNI.new_AndroidOutImageRead_t(), true);
  }

}
