/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule.aim;

public class PictureTransformModuleExt extends PictureTransformModule {
  private long swigCPtr;

  protected PictureTransformModuleExt(long cPtr, boolean cMemoryOwn) {
    super(AIMJNI.PictureTransformModuleExt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PictureTransformModuleExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_PictureTransformModuleExt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PictureTransformModuleExt() {
    this(AIMJNI.new_PictureTransformModuleExt(), true);
  }

  public void Tick() {
    AIMJNI.PictureTransformModuleExt_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.PictureTransformModuleExt_Stop(swigCPtr, this);
  }

}
