/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.picturetransformmodule.aim;

public class vector_long {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vector_long(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_long obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_vector_long(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_long() {
    this(AIMJNI.new_vector_long__SWIG_0(), true);
  }

  public vector_long(long n) {
    this(AIMJNI.new_vector_long__SWIG_1(n), true);
  }

  public long size() {
    return AIMJNI.vector_long_size(swigCPtr, this);
  }

  public long capacity() {
    return AIMJNI.vector_long_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AIMJNI.vector_long_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AIMJNI.vector_long_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AIMJNI.vector_long_clear(swigCPtr, this);
  }

  public void add(int x) {
    AIMJNI.vector_long_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return AIMJNI.vector_long_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    AIMJNI.vector_long_set(swigCPtr, this, i, val);
  }

}
