/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.bmptojpgmodule.aim;

public class BmpToJpgModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BmpToJpgModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BmpToJpgModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_BmpToJpgModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(SWIGTYPE_p_std__string name) {
    AIMJNI.BmpToJpgModule_Init(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
  }

  public Param GetParam() {
    long cPtr = AIMJNI.BmpToJpgModule_GetParam(swigCPtr, this);
    return (cPtr == 0) ? null : new Param(cPtr, false);
  }

  public void Tick() {
    AIMJNI.BmpToJpgModule_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.BmpToJpgModule_Stop(swigCPtr, this);
  }

  public vector_int readBmp(boolean blocking) {
    long cPtr = AIMJNI.BmpToJpgModule_readBmp__SWIG_0(swigCPtr, this, blocking);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public vector_int readBmp() {
    long cPtr = AIMJNI.BmpToJpgModule_readBmp__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new vector_int(cPtr, false);
  }

  public void androidWriteBmp(vector_int input) {
    AIMJNI.BmpToJpgModule_androidWriteBmp(swigCPtr, this, vector_int.getCPtr(input), input);
  }

  public boolean writeJpg(String output) {
    return AIMJNI.BmpToJpgModule_writeJpg(swigCPtr, this, output);
  }

  public AndroidJpgRead_t androidReadJpg() {
    return new AndroidJpgRead_t(AIMJNI.BmpToJpgModule_androidReadJpg(swigCPtr, this), true);
  }

}
