/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.bmptojpgmodule.aim;

public class BmpToJpgModuleExt extends BmpToJpgModule {
  private long swigCPtr;

  protected BmpToJpgModuleExt(long cPtr, boolean cMemoryOwn) {
    super(AIMJNI.BmpToJpgModuleExt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BmpToJpgModuleExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_BmpToJpgModuleExt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BmpToJpgModuleExt() {
    this(AIMJNI.new_BmpToJpgModuleExt(), true);
  }

  public void Tick() {
    AIMJNI.BmpToJpgModuleExt_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.BmpToJpgModuleExt_Stop(swigCPtr, this);
  }

}
