/**
 * IDL description of the AvgBrightnessModule
 *
 * This file is automatically parsed by the rurbuilder backends for the omniidl compiler. The names of the functions
 * will become port identifiers. The names of the function variables are not used. 
 *
 * The syntax of the IDL file also allows for "inout", but not all middlewares will accept this yet.
 */

#pragma author               Bart van Vliet
#pragma copyright            DoBots
#pragma date                 dec 17, 2013
#pragma license              GNU General Lesser Public Licence

// Recommended namespace "rur"
module rur {

// The command-line parameter (this struct is required)
struct Param {
  // multiple modules can be addressed in parallel, killed, etc. using "module_id"
  string module_id;
};

// Typedef for array of integers
typedef sequence<long> long_seq;

// The public interface of AvgBrightnessModule
interface AvgBrightnessModule {

	// Input image in the form of a jpg file encoded as a base64 string
	void Image(in string base_64);

	// Output the average brightness of the image
	void Brightness(out float output);

	// Change settings of the camera module
	void CommandOut(out string output);
};

};
