/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.brightnesstomorsemodule.aim;

public class BrightnessToMorseModuleExt extends BrightnessToMorseModule {
  private long swigCPtr;

  protected BrightnessToMorseModuleExt(long cPtr, boolean cMemoryOwn) {
    super(AIMJNI.BrightnessToMorseModuleExt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BrightnessToMorseModuleExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_BrightnessToMorseModuleExt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BrightnessToMorseModuleExt() {
    this(AIMJNI.new_BrightnessToMorseModuleExt(), true);
  }

  public void Tick() {
    AIMJNI.BrightnessToMorseModuleExt_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.BrightnessToMorseModuleExt_Stop(swigCPtr, this);
  }

}
