/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.brightnesstomorsemodule.aim;

public class vector_double {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vector_double(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_double obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_vector_double(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_double() {
    this(AIMJNI.new_vector_double__SWIG_0(), true);
  }

  public vector_double(long n) {
    this(AIMJNI.new_vector_double__SWIG_1(n), true);
  }

  public long size() {
    return AIMJNI.vector_double_size(swigCPtr, this);
  }

  public long capacity() {
    return AIMJNI.vector_double_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AIMJNI.vector_double_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AIMJNI.vector_double_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AIMJNI.vector_double_clear(swigCPtr, this);
  }

  public void add(double x) {
    AIMJNI.vector_double_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return AIMJNI.vector_double_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    AIMJNI.vector_double_set(swigCPtr, this, i, val);
  }

}
