/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.jpgtobmpmodule.aim;

public class JpgToBmpModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JpgToBmpModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JpgToBmpModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_JpgToBmpModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(SWIGTYPE_p_std__string name) {
    AIMJNI.JpgToBmpModule_Init(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
  }

  public Param GetParam() {
    long cPtr = AIMJNI.JpgToBmpModule_GetParam(swigCPtr, this);
    return (cPtr == 0) ? null : new Param(cPtr, false);
  }

  public void Tick() {
    AIMJNI.JpgToBmpModule_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.JpgToBmpModule_Stop(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string readJpg(boolean blocking) {
    long cPtr = AIMJNI.JpgToBmpModule_readJpg__SWIG_0(swigCPtr, this, blocking);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public SWIGTYPE_p_std__string readJpg() {
    long cPtr = AIMJNI.JpgToBmpModule_readJpg__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void androidWriteJpg(String input) {
    AIMJNI.JpgToBmpModule_androidWriteJpg(swigCPtr, this, input);
  }

  public boolean writeBmp(vector_int output) {
    return AIMJNI.JpgToBmpModule_writeBmp(swigCPtr, this, vector_int.getCPtr(output), output);
  }

  public AndroidBmpRead_t androidReadBmp() {
    return new AndroidBmpRead_t(AIMJNI.JpgToBmpModule_androidReadBmp(swigCPtr, this), true);
  }

}
