/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.jpgtobmpmodule.aim;

public class JpgToBmpModuleExt extends JpgToBmpModule {
  private long swigCPtr;

  protected JpgToBmpModuleExt(long cPtr, boolean cMemoryOwn) {
    super(AIMJNI.JpgToBmpModuleExt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JpgToBmpModuleExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_JpgToBmpModuleExt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public JpgToBmpModuleExt() {
    this(AIMJNI.new_JpgToBmpModuleExt(), true);
  }

  public void Tick() {
    AIMJNI.JpgToBmpModuleExt_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.JpgToBmpModuleExt_Stop(swigCPtr, this);
  }

}
