/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.avgbrightnessmodule.aim;

public class AvgBrightnessModule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AvgBrightnessModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AvgBrightnessModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_AvgBrightnessModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(SWIGTYPE_p_std__string name) {
    AIMJNI.AvgBrightnessModule_Init(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
  }

  public Param GetParam() {
    long cPtr = AIMJNI.AvgBrightnessModule_GetParam(swigCPtr, this);
    return (cPtr == 0) ? null : new Param(cPtr, false);
  }

  public void Tick() {
    AIMJNI.AvgBrightnessModule_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.AvgBrightnessModule_Stop(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string readImage(boolean blocking) {
    long cPtr = AIMJNI.AvgBrightnessModule_readImage__SWIG_0(swigCPtr, this, blocking);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public SWIGTYPE_p_std__string readImage() {
    long cPtr = AIMJNI.AvgBrightnessModule_readImage__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void androidWriteImage(String base_64) {
    AIMJNI.AvgBrightnessModule_androidWriteImage(swigCPtr, this, base_64);
  }

  public boolean writeBrightness(float output) {
    return AIMJNI.AvgBrightnessModule_writeBrightness(swigCPtr, this, output);
  }

  public AndroidBrightnessRead_t androidReadBrightness() {
    return new AndroidBrightnessRead_t(AIMJNI.AvgBrightnessModule_androidReadBrightness(swigCPtr, this), true);
  }

}
