/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dobots.avgbrightnessmodule.aim;

public class AvgBrightnessModuleExt extends AvgBrightnessModule {
  private long swigCPtr;

  protected AvgBrightnessModuleExt(long cPtr, boolean cMemoryOwn) {
    super(AIMJNI.AvgBrightnessModuleExt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AvgBrightnessModuleExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIMJNI.delete_AvgBrightnessModuleExt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AvgBrightnessModuleExt() {
    this(AIMJNI.new_AvgBrightnessModuleExt(), true);
  }

  public void Tick() {
    AIMJNI.AvgBrightnessModuleExt_Tick(swigCPtr, this);
  }

  public boolean Stop() {
    return AIMJNI.AvgBrightnessModuleExt_Stop(swigCPtr, this);
  }

}
